name: Build APK Android 16
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
      - name: Fix for Android 16
        run: |
          sed -i 's/compileSdk.*/compileSdkVersion 36/g; s/targetSdk.*/targetSdkVersion 36/g' app/build.gradle
          sed -i "s/id 'com.android.application'.*/id 'com.android.application' version '8.5.0' apply false/" build.gradle
      - name: Build with Gradle
        run: gradle assembleRelease --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: KR-EQ-Android16-FINAL
          path: app/build/outputs/apk/release/*.apk
